// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class BasicOperationsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void basicOperations() {
    // Test name: Basic Operations
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("https://www.google.com/");
    // 2 | setWindowSize | 1536x864 | 
    driver.manage().window().setSize(new Dimension(1536, 864));
    // 3 | click | id=APjFqb | 
    driver.findElement(By.id("APjFqb")).click();
    // 4 | type | id=APjFqb | calculator
    driver.findElement(By.id("APjFqb")).sendKeys("calculator");
    // 5 | click | name=btnK | 
    driver.findElement(By.name("btnK")).click();
    // 6 | click | css=.XH1CIc | 
    driver.findElement(By.cssSelector(".XH1CIc")).click();
    // 7 | click | css=tr:nth-child(3) > td:nth-child(2) > .A2W7l > .XRsWPe | 
    driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(2) > .A2W7l > .XRsWPe")).click();
    // 8 | click | css=tr:nth-child(3) > td:nth-child(1) > .A2W7l > .XRsWPe | 
    driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(1) > .A2W7l > .XRsWPe")).click();
    // 9 | click | css=tr:nth-child(3) > td:nth-child(1) > .A2W7l > .XRsWPe | 
    driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(1) > .A2W7l > .XRsWPe")).click();
    // 10 | doubleClick | css=tr:nth-child(3) > td:nth-child(1) > .A2W7l > .XRsWPe | 
    {
      WebElement element = driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(1) > .A2W7l > .XRsWPe"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    // 11 | click | css=tr:nth-child(4) > td:nth-child(1) > .A2W7l > .XRsWPe | 
    driver.findElement(By.cssSelector("tr:nth-child(4) > td:nth-child(1) > .A2W7l > .XRsWPe")).click();
    // 12 | click | css=td:nth-child(4) .XRsWPe:nth-child(2) | 
    driver.findElement(By.cssSelector("td:nth-child(4) .XRsWPe:nth-child(2)")).click();
    // 13 | click | css=tr:nth-child(3) > td:nth-child(1) > .A2W7l > .XRsWPe | 
    driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(1) > .A2W7l > .XRsWPe")).click();
    // 14 | click | css=tr:nth-child(4) > td:nth-child(1) > .A2W7l > .XRsWPe | 
    driver.findElement(By.cssSelector("tr:nth-child(4) > td:nth-child(1) > .A2W7l > .XRsWPe")).click();
    // 15 | click | css=tr:nth-child(2) .mF5fo > .XRsWPe | 
    driver.findElement(By.cssSelector("tr:nth-child(2) .mF5fo > .XRsWPe")).click();
    // 16 | click | css=tr:nth-child(2) > td:nth-child(1) > .A2W7l > .XRsWPe | 
    driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(1) > .A2W7l > .XRsWPe")).click();
    // 17 | click | css=tr:nth-child(2) > td:nth-child(2) > .A2W7l > .XRsWPe | 
    driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(2) > .A2W7l > .XRsWPe")).click();
    // 18 | click | css=tr:nth-child(2) > td:nth-child(3) > .A2W7l > .XRsWPe | 
    driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(3) > .A2W7l > .XRsWPe")).click();
    // 19 | click | css=.UUhRt | 
    driver.findElement(By.cssSelector(".UUhRt")).click();
    // 20 | close |  | 
    driver.close();
  }
}
