// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class DragNDropTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void dragNDrop() {
    // Test name: Drag N Drop
    // Step # | name | target | value
    // 1 | open | /cdk/drag-drop/examples | 
    driver.get("https://material.angular.io/cdk/drag-drop/examples");
    // 2 | storeXpathCount | xpath=//div[@id="cdk-drop-list-0"]//div[contains(., "Pick up groceries")] | i
    vars.put("i", driver.findElements(By.xpath("//div[@id=\"cdk-drop-list-0\"]//div[contains(., \"Pick up groceries\")]")).size());
    // 3 | echo | ${i} | 
    System.out.println(vars.get("i").toString());
    // 4 | dragAndDropToObject | xpath=//div[@id="cdk-drop-list-0"]//div[contains(., "Pick up groceries")] | id=cdk-drop-list-1
    {
      WebElement dragged = driver.findElement(By.xpath("//div[@id=\"cdk-drop-list-0\"]//div[contains(., \"Pick up groceries\")]"));
      WebElement dropped = driver.findElement(By.id("cdk-drop-list-1"));
      Actions builder = new Actions(driver);
      builder.dragAndDrop(dragged, dropped).perform();
    }
    // 5 | close |  | 
    driver.close();
  }
}
