// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class EmailReadingTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void emailReading() {
    // Test name: Email Reading
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("https://mail.nitrkl.ac.in/");
    // 2 | setWindowSize | 845x864 | 
    driver.manage().window().setSize(new Dimension(845, 864));
    // 3 | click | css=#zlif__CLV-main__-2408__su > span:nth-child(1) | 
    driver.findElement(By.cssSelector("#zlif__CLV-main__-2408__su > span:nth-child(1)")).click();
    // 4 | selectFrame | index=1 | 
    driver.switchTo().frame(1);
    // 5 | click | linkText=https://app.inspiredstudy.com/register | 
    driver.findElement(By.linkText("https://app.inspiredstudy.com/register")).click();
    // 6 | close |  | 
    driver.close();
  }
}
