// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class FormFillingTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void formFilling() {
    // Test name: Form Filling
    // Step # | name | target | value
    // 1 | open | /forms/d/e/1FAIpQLSeI8_vYyaJgM7SJM4Y9AWfLq-tglWZh6yt7bEXEOJr_L-hV1A/viewform?formkey=dGx0b1ZrTnoyZDgtYXItMWVBdVlQQWc6MQ | 
    driver.get("https://docs.google.com/forms/d/e/1FAIpQLSeI8_vYyaJgM7SJM4Y9AWfLq-tglWZh6yt7bEXEOJr_L-hV1A/viewform?formkey=dGx0b1ZrTnoyZDgtYXItMWVBdVlQQWc6MQ");
    // 2 | setWindowSize | 1552x880 | 
    driver.manage().window().setSize(new Dimension(1552, 880));
    // 3 | click | css=.aCsJod | 
    driver.findElement(By.cssSelector(".aCsJod")).click();
    // 4 | click | css=.aCsJod | 
    driver.findElement(By.cssSelector(".aCsJod")).click();
    // 5 | click | css=.whsOnd | 
    driver.findElement(By.cssSelector(".whsOnd")).click();
    // 6 | type | css=.whsOnd | This is selenium testing
    driver.findElement(By.cssSelector(".whsOnd")).sendKeys("This is selenium testing");
    // 7 | click | css=.KHxj8b | 
    driver.findElement(By.cssSelector(".KHxj8b")).click();
    // 8 | type | css=.KHxj8b | By selenium testing we can test website response to user commands and verify if it is working properly. This test is conducted by selenium IDE.
    driver.findElement(By.cssSelector(".KHxj8b")).sendKeys("By selenium testing we can test website response to user commands and verify if it is working properly. This test is conducted by selenium IDE.");
    // 9 | click | css=#i16 .AB7Lab | 
    driver.findElement(By.cssSelector("#i16 .AB7Lab")).click();
    // 10 | click | css=.eBFwI:nth-child(2) .aDTYNe | 
    driver.findElement(By.cssSelector(".eBFwI:nth-child(2) .aDTYNe")).click();
    // 11 | click | id=i27 | 
    driver.findElement(By.id("i27")).click();
    // 12 | click | css=.KKjvXb > .vRMGwf | 
    driver.findElement(By.cssSelector(".KKjvXb > .vRMGwf")).click();
    // 13 | click | css=.OA0qNb > .KKjvXb > .vRMGwf | 
    driver.findElement(By.cssSelector(".OA0qNb > .KKjvXb > .vRMGwf")).click();
    // 14 | click | xpath=//div[@class="N9Qcwe"]//div[@data-value="4"] | 
    driver.findElement(By.xpath("//div[@class=\"N9Qcwe\"]//div[@data-value=\"4\"]")).click();
    // 15 | click | xpath=//form[@id='mG61Hd']/div[2]/div/div[2]/div[7]/div/div/div[2]/div/div/div/div[2]/span/div[3]/div/div/div[3]/div | 
    driver.findElement(By.xpath("//form[@id=\'mG61Hd\']/div[2]/div/div[2]/div[7]/div/div/div[2]/div/div/div/div[2]/span/div[3]/div/div/div[3]/div")).click();
    // 16 | click | xpath=//form[@id='mG61Hd']/div[2]/div/div[2]/div[7]/div/div/div[2]/div/div/div/div[4]/span/div[4]/div/div/div[3]/div | 
    driver.findElement(By.xpath("//form[@id=\'mG61Hd\']/div[2]/div/div[2]/div[7]/div/div/div[2]/div/div/div/div[4]/span/div[4]/div/div/div[3]/div")).click();
    // 17 | click | xpath=//form[@id='mG61Hd']/div[2]/div/div[2]/div[7]/div/div/div[2]/div/div/div/div[6]/span/div[4]/div/div/div[3]/div | 
    driver.findElement(By.xpath("//form[@id=\'mG61Hd\']/div[2]/div/div[2]/div[7]/div/div/div[2]/div/div/div/div[6]/span/div[4]/div/div/div[3]/div")).click();
    // 18 | click | xpath=//form[@id='mG61Hd']/div[2]/div/div[2]/div[7]/div/div/div[2]/div/div/div/div[8]/span/div[3]/div/div/div[3]/div | 
    driver.findElement(By.xpath("//form[@id=\'mG61Hd\']/div[2]/div/div[2]/div[7]/div/div/div[2]/div/div/div/div[8]/span/div[3]/div/div/div[3]/div")).click();
    // 19 | click | css=.Y5sE8d > .l4V7wb | 
    driver.findElement(By.cssSelector(".Y5sE8d > .l4V7wb")).click();
    // 20 | waitForElementPresent | xpath=//a[text()="Submit another response"] | 5000
    {
      WebDriverWait wait = new WebDriverWait(driver, 5);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//a[text()=\"Submit another response\"]")));
    }
    // 21 | close |  | 
    driver.close();
  }
}
