// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class NavigateLinksTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void navigateLinks() {
    // Test name: Navigate Links
    // Step # | name | target | value
    // 1 | open | https://en.wikipedia.org/wiki/Main_Page | 
    driver.get("https://en.wikipedia.org/wiki/Main_Page");
    // 2 | times | 5 | 
    Integer times = 5;
    for(int i = 0; i < times; i++) {
      // 3 | storeXpathCount | xpath=(//a)[contains(@href, "en")] | linkCount
      vars.put("linkCount", driver.findElements(By.xpath("(//a)[contains(@href, \"en\")]")).size());
      // 4 | echo | ${linkCount} | 
      System.out.println(vars.get("linkCount").toString());
      // 5 | executeScript | return Math.floor(Math.random() * ${linkCount}) | randomNumber
      vars.put("randomNumber", js.executeScript("return Math.floor(Math.random() * arguments[0])", vars.get("linkCount")));
      // 6 | echo | ${randomNumber} | 
      System.out.println(vars.get("randomNumber").toString());
      // 7 | storeText | xpath=(//a[contains(@href, "en")])[${randomNumber}] | linkText
      vars.put("linkText", driver.findElement(By.xpath("(//a[contains(@href, \"en\")])[vars.get("randomNumber").toString()]")).getText());
      // 8 | echo | ${linkText} | 
      System.out.println(vars.get("linkText").toString());
      // 9 | click | xpath=(//a[contains(@href, "en")])[${randomNumber}] | 
      driver.findElement(By.xpath("(//a[contains(@href, \"en\")])[vars.get("randomNumber").toString()]")).click();
      // 10 | end |  | 
    }
    // 11 | close |  | 
    driver.close();
  }
}
