// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SearchNPlayTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void searchNPlay() {
    // Test name: Search N Play
    // Step # | name | target | value
    // 1 | open | /home | 
    driver.get("https://aniwatch.to/home");
    // 2 | setWindowSize | 1536x864 | 
    driver.manage().window().setSize(new Dimension(1536, 864));
    // 3 | click | name=keyword | 
    driver.findElement(By.name("keyword")).click();
    // 4 | type | name=keyword | jujutsu kaisen
    driver.findElement(By.name("keyword")).sendKeys("jujutsu kaisen");
    // 5 | click | css=.search-icon > .fas | 
    driver.findElement(By.cssSelector(".search-icon > .fas")).click();
    // 6 | click | linkText=Jujutsu Kaisen 2nd Season | 
    driver.findElement(By.linkText("Jujutsu Kaisen 2nd Season")).click();
    // 7 | click | linkText=Watch now | 
    driver.findElement(By.linkText("Watch now")).click();
    // 8 | click | css=.ssl-item:nth-child(17) .ep-name | 
    driver.findElement(By.cssSelector(".ssl-item:nth-child(17) .ep-name")).click();
    // 9 | selectFrame | index=0 | 
    driver.switchTo().frame(0);
    // 10 | selectFrame | relative=parent | 
    driver.switchTo().defaultContent();
    // 11 | close |  | 
    driver.close();
  }
}
