// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ViewLehenghaTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void viewLehengha() {
    // Test name: View Lehengha
    // Step # | name | target | value
    // 1 | open | /collections/lehenga | 
    driver.get("https://houseofpanchhi.com/collections/lehenga");
    // 2 | setWindowSize | 1536x864 | 
    driver.manage().window().setSize(new Dimension(1536, 864));
    // 3 | click | css=.grid__item:nth-child(1) .grid-product__title | 
    driver.findElement(By.cssSelector(".grid__item:nth-child(1) .grid-product__title")).click();
    // 4 | click | css=.animation-delay-6 | 
    driver.findElement(By.cssSelector(".animation-delay-6")).click();
    // 5 | click | css=.animation-delay-9 | 
    driver.findElement(By.cssSelector(".animation-delay-9")).click();
    // 6 | click | css=.animation-delay-12 | 
    driver.findElement(By.cssSelector(".animation-delay-12")).click();
    // 7 | click | css=.ymq-attrib-item-1tem1_2 > .ymq-option-value | 
    driver.findElement(By.cssSelector(".ymq-attrib-item-1tem1_2 > .ymq-option-value")).click();
    // 8 | click | css=.variant-input > .color-swatch--lavender | 
    driver.findElement(By.cssSelector(".variant-input > .color-swatch--lavender")).click();
    // 9 | click | css=.ymq-attrib-item-1tem2_2 | 
    driver.findElement(By.cssSelector(".ymq-attrib-item-1tem2_2")).click();
    // 10 | click | css=.ymq-attrib-item-1tem3_3 | 
    driver.findElement(By.cssSelector(".ymq-attrib-item-1tem3_3")).click();
    // 11 | click | css=.icon-plus | 
    driver.findElement(By.cssSelector(".icon-plus")).click();
    // 12 | close |  | 
    driver.close();
  }
}
