# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAlert():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_alert(self):
    # Test name: Alert
    # Step # | name | target | value
    # 1 | open | /jsref/tryit.asp?filename=tryjsref_alert | 
    self.driver.get("https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_alert")
    # 2 | setWindowSize | 1552x880 | 
    self.driver.set_window_size(1552, 880)
    # 3 | selectFrame | index=0 | 
    self.driver.switch_to.frame(0)
    # 4 | click | css=button | 
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    # 5 | assertAlert | Hello! I am an alert box! | 
    assert self.driver.switch_to.alert.text == "Hello! I am an alert box!"
    # 6 | close |  | 
    self.driver.close()
  
