# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAttachmentDownload():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_attachmentDownload(self):
    # Test name: Attachment Download
    # Step # | name | target | value
    # 1 | open | /nitris/Student/Home/Home.aspx | 
    self.driver.get("https://eapplication.nitrkl.ac.in/nitris/Student/Home/Home.aspx")
    # 2 | setWindowSize | 850x864 | 
    self.driver.set_window_size(850, 864)
    # 3 | click | css=.mdi-comment-processing | 
    self.driver.find_element(By.CSS_SELECTOR, ".mdi-comment-processing").click()
    # 4 | click | css=.message-item:nth-child(2) > .mail-contnet | 
    self.driver.find_element(By.CSS_SELECTOR, ".message-item:nth-child(2) > .mail-contnet").click()
    # 5 | click | id=ContentPlaceHolder2_hypPreview | 
    self.driver.find_element(By.ID, "ContentPlaceHolder2_hypPreview").click()
    # 6 | close |  | 
    self.driver.close()
  
