# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestFormFilling():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_formFilling(self):
    # Test name: Form Filling
    # Step # | name | target | value
    # 1 | open | /forms/d/e/1FAIpQLSeI8_vYyaJgM7SJM4Y9AWfLq-tglWZh6yt7bEXEOJr_L-hV1A/viewform?formkey=dGx0b1ZrTnoyZDgtYXItMWVBdVlQQWc6MQ | 
    self.driver.get("https://docs.google.com/forms/d/e/1FAIpQLSeI8_vYyaJgM7SJM4Y9AWfLq-tglWZh6yt7bEXEOJr_L-hV1A/viewform?formkey=dGx0b1ZrTnoyZDgtYXItMWVBdVlQQWc6MQ")
    # 2 | setWindowSize | 1552x880 | 
    self.driver.set_window_size(1552, 880)
    # 3 | click | css=.aCsJod | 
    self.driver.find_element(By.CSS_SELECTOR, ".aCsJod").click()
    # 4 | click | css=.aCsJod | 
    self.driver.find_element(By.CSS_SELECTOR, ".aCsJod").click()
    # 5 | click | css=.whsOnd | 
    self.driver.find_element(By.CSS_SELECTOR, ".whsOnd").click()
    # 6 | type | css=.whsOnd | This is selenium testing
    self.driver.find_element(By.CSS_SELECTOR, ".whsOnd").send_keys("This is selenium testing")
    # 7 | click | css=.KHxj8b | 
    self.driver.find_element(By.CSS_SELECTOR, ".KHxj8b").click()
    # 8 | type | css=.KHxj8b | By selenium testing we can test website response to user commands and verify if it is working properly. This test is conducted by selenium IDE.
    self.driver.find_element(By.CSS_SELECTOR, ".KHxj8b").send_keys("By selenium testing we can test website response to user commands and verify if it is working properly. This test is conducted by selenium IDE.")
    # 9 | click | css=#i16 .AB7Lab | 
    self.driver.find_element(By.CSS_SELECTOR, "#i16 .AB7Lab").click()
    # 10 | click | css=.eBFwI:nth-child(2) .aDTYNe | 
    self.driver.find_element(By.CSS_SELECTOR, ".eBFwI:nth-child(2) .aDTYNe").click()
    # 11 | click | id=i27 | 
    self.driver.find_element(By.ID, "i27").click()
    # 12 | click | css=.KKjvXb > .vRMGwf | 
    self.driver.find_element(By.CSS_SELECTOR, ".KKjvXb > .vRMGwf").click()
    # 13 | click | css=.OA0qNb > .KKjvXb > .vRMGwf | 
    self.driver.find_element(By.CSS_SELECTOR, ".OA0qNb > .KKjvXb > .vRMGwf").click()
    # 14 | click | xpath=//div[@class="N9Qcwe"]//div[@data-value="4"] | 
    self.driver.find_element(By.XPATH, "//div[@class=\"N9Qcwe\"]//div[@data-value=\"4\"]").click()
    # 15 | click | xpath=//form[@id='mG61Hd']/div[2]/div/div[2]/div[7]/div/div/div[2]/div/div/div/div[2]/span/div[3]/div/div/div[3]/div | 
    self.driver.find_element(By.XPATH, "//form[@id=\'mG61Hd\']/div[2]/div/div[2]/div[7]/div/div/div[2]/div/div/div/div[2]/span/div[3]/div/div/div[3]/div").click()
    # 16 | click | xpath=//form[@id='mG61Hd']/div[2]/div/div[2]/div[7]/div/div/div[2]/div/div/div/div[4]/span/div[4]/div/div/div[3]/div | 
    self.driver.find_element(By.XPATH, "//form[@id=\'mG61Hd\']/div[2]/div/div[2]/div[7]/div/div/div[2]/div/div/div/div[4]/span/div[4]/div/div/div[3]/div").click()
    # 17 | click | xpath=//form[@id='mG61Hd']/div[2]/div/div[2]/div[7]/div/div/div[2]/div/div/div/div[6]/span/div[4]/div/div/div[3]/div | 
    self.driver.find_element(By.XPATH, "//form[@id=\'mG61Hd\']/div[2]/div/div[2]/div[7]/div/div/div[2]/div/div/div/div[6]/span/div[4]/div/div/div[3]/div").click()
    # 18 | click | xpath=//form[@id='mG61Hd']/div[2]/div/div[2]/div[7]/div/div/div[2]/div/div/div/div[8]/span/div[3]/div/div/div[3]/div | 
    self.driver.find_element(By.XPATH, "//form[@id=\'mG61Hd\']/div[2]/div/div[2]/div[7]/div/div/div[2]/div/div/div/div[8]/span/div[3]/div/div/div[3]/div").click()
    # 19 | click | css=.Y5sE8d > .l4V7wb | 
    self.driver.find_element(By.CSS_SELECTOR, ".Y5sE8d > .l4V7wb").click()
    # 20 | waitForElementPresent | xpath=//a[text()="Submit another response"] | 5000
    WebDriverWait(self.driver, 5).until(expected_conditions.presence_of_element_located((By.XPATH, "//a[text()=\"Submit another response\"]")))
    # 21 | close |  | 
    self.driver.close()
  
