# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestProductSearch():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_productSearch(self):
    # Test name: Product Search
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://www.amazon.in/")
    # 2 | setWindowSize | 1552x880 | 
    self.driver.set_window_size(1552, 880)
    # 3 | click | id=twotabsearchtextbox | 
    self.driver.find_element(By.ID, "twotabsearchtextbox").click()
    # 4 | type | id=twotabsearchtextbox | macbook pro m3
    self.driver.find_element(By.ID, "twotabsearchtextbox").send_keys("macbook pro m3")
    # 5 | click | id=nav-search-submit-button | 
    self.driver.find_element(By.ID, "nav-search-submit-button").click()
    # 6 | click | xpath=//a/span[text()="2023 MacBook Air laptop with M2 chip: 38.91cm (15.3 inch) Liquid Retina display, 8GB RAM 256GB SSD storage, backlit keyboard, 1080p FaceTime HD camera,Touch ID. Works with iPhone/iPad; Starlight"] | 
    self.vars["window_handles"] = self.driver.window_handles
    # 7 | storeWindowHandle | root | 
    self.driver.find_element(By.XPATH, "//a/span[text()=\"2023 MacBook Air laptop with M2 chip: 38.91cm (15.3 inch) Liquid Retina display, 8GB RAM 256GB SSD storage, backlit keyboard, 1080p FaceTime HD camera,Touch ID. Works with iPhone/iPad; Starlight\"]").click()
    # 8 | selectWindow | handle=${productPage} | 
    self.vars["productPage"] = self.wait_for_window(2000)
    # 9 | assertElementPresent | xpath=//h1/span[text()="        Apple 2023 MacBook Air laptop with M2 chip: 38.91cm (15.3 inch) Liquid Retina display, 8GB RAM 256GB SSD storage, backlit keyboard, 1080p FaceTime HD camera,Touch ID. Works with iPhone/iPad; Starlight       "] | 
    self.vars["root"] = self.driver.current_window_handle
    # 10 | close |  | 
    self.driver.switch_to.window(self.vars["productPage"])
    # 11 | selectWindow | handle=${root} | 
    elements = self.driver.find_elements(By.XPATH, "//h1/span[text()=\"        Apple 2023 MacBook Air laptop with M2 chip: 38.91cm (15.3 inch) Liquid Retina display, 8GB RAM 256GB SSD storage, backlit keyboard, 1080p FaceTime HD camera,Touch ID. Works with iPhone/iPad; Starlight       \"]")
    assert len(elements) > 0
    # 12 | close |  | 
    self.driver.close()
    self.driver.switch_to.window(self.vars["root"])
    self.driver.close()
  
