# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSearchNPlay():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_searchNPlay(self):
    # Test name: Search N Play
    # Step # | name | target | value
    # 1 | open | /home | 
    self.driver.get("https://aniwatch.to/home")
    # 2 | setWindowSize | 1536x864 | 
    self.driver.set_window_size(1536, 864)
    # 3 | click | name=keyword | 
    self.driver.find_element(By.NAME, "keyword").click()
    # 4 | type | name=keyword | jujutsu kaisen
    self.driver.find_element(By.NAME, "keyword").send_keys("jujutsu kaisen")
    # 5 | click | css=.search-icon > .fas | 
    self.driver.find_element(By.CSS_SELECTOR, ".search-icon > .fas").click()
    # 6 | click | linkText=Jujutsu Kaisen 2nd Season | 
    self.driver.find_element(By.LINK_TEXT, "Jujutsu Kaisen 2nd Season").click()
    # 7 | click | linkText=Watch now | 
    self.driver.find_element(By.LINK_TEXT, "Watch now").click()
    # 8 | click | css=.ssl-item:nth-child(17) .ep-name | 
    self.driver.find_element(By.CSS_SELECTOR, ".ssl-item:nth-child(17) .ep-name").click()
    # 9 | selectFrame | index=0 | 
    self.driver.switch_to.frame(0)
    # 10 | selectFrame | relative=parent | 
    self.driver.switch_to.default_content()
    # 11 | close |  | 
    self.driver.close()
  
