# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestViewLehengha():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_viewLehengha(self):
    # Test name: View Lehengha
    # Step # | name | target | value
    # 1 | open | /collections/lehenga | 
    self.driver.get("https://houseofpanchhi.com/collections/lehenga")
    # 2 | setWindowSize | 1536x864 | 
    self.driver.set_window_size(1536, 864)
    # 3 | click | css=.grid__item:nth-child(1) .grid-product__title | 
    self.driver.find_element(By.CSS_SELECTOR, ".grid__item:nth-child(1) .grid-product__title").click()
    # 4 | click | css=.animation-delay-6 | 
    self.driver.find_element(By.CSS_SELECTOR, ".animation-delay-6").click()
    # 5 | click | css=.animation-delay-9 | 
    self.driver.find_element(By.CSS_SELECTOR, ".animation-delay-9").click()
    # 6 | click | css=.animation-delay-12 | 
    self.driver.find_element(By.CSS_SELECTOR, ".animation-delay-12").click()
    # 7 | click | css=.ymq-attrib-item-1tem1_2 > .ymq-option-value | 
    self.driver.find_element(By.CSS_SELECTOR, ".ymq-attrib-item-1tem1_2 > .ymq-option-value").click()
    # 8 | click | css=.variant-input > .color-swatch--lavender | 
    self.driver.find_element(By.CSS_SELECTOR, ".variant-input > .color-swatch--lavender").click()
    # 9 | click | css=.ymq-attrib-item-1tem2_2 | 
    self.driver.find_element(By.CSS_SELECTOR, ".ymq-attrib-item-1tem2_2").click()
    # 10 | click | css=.ymq-attrib-item-1tem3_3 | 
    self.driver.find_element(By.CSS_SELECTOR, ".ymq-attrib-item-1tem3_3").click()
    # 11 | click | css=.icon-plus | 
    self.driver.find_element(By.CSS_SELECTOR, ".icon-plus").click()
    # 12 | close |  | 
    self.driver.close()
  
