# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestWordToPDF():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_wordToPDF(self):
    # Test name: Word To PDF
    # Step # | name | target | value
    # 1 | open | /pdf-to-word | 
    self.driver.get("https://smallpdf.com/pdf-to-word")
    # 2 | setWindowSize | 850x864 | 
    self.driver.set_window_size(850, 864)
    # 3 | click | id=__picker-input | 
    self.driver.find_element(By.ID, "__picker-input").click()
    # 4 | type | id=__picker-input | C:\Users\Yash\Downloads\Assignment 1 Equivalence Classes.docx
    self.driver.find_element(By.ID, "__picker-input").send_keys("C:\\Users\\Yash\\Downloads\\Assignment 1 Equivalence Classes.docx")
    # 5 | click | css=.kHOHNI .r5zwp6-3:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, ".kHOHNI .r5zwp6-3:nth-child(2)").click()
    # 6 | close |  | 
    self.driver.close()
  
